"""Add initial inputdata table

Revision ID: d9ebb910286d
Revises: 
Create Date: 2024-02-23 10:04:58.359211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9ebb910286d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('input_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('github_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_input_data_id'), 'input_data', ['id'], unique=False)
    op.create_table('output_diffs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('diff', sa.Text(), nullable=True),
    sa.Column('input_data_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['input_data_id'], ['input_data.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_output_diffs_id'), 'output_diffs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_output_diffs_id'), table_name='output_diffs')
    op.drop_table('output_diffs')
    op.drop_index(op.f('ix_input_data_id'), table_name='input_data')
    op.drop_table('input_data')
    # ### end Alembic commands ###
